services:
  backend:
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

  frontend:
    build:
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
